language: php

cache:
  directories:
    - $HOME/.composer/cache
    
before_install:
  - wget http://get.sensiolabs.org/php-cs-fixer.phar
  - composer self-update
      
before_script:
  - echo "extension = apc.so" >> ~/.phpenv/versions/$(phpenv version-name)/etc/php.ini
        
matrix:
  fast_finish: true
  include:
    - php: 5.5
    - php: 5.6
      env:
        - EXECUTE_CS_CHECK=true
    - php: 7
    - php: hhvm
  allow_failures:
    - php: 7
    - php: hhvm

install:
  - travis_retry composer install --no-interaction --ignore-platform-reqs --prefer-source
  - composer info -i

script:
  - (phpunit -c phpunit.xml)
  - if [[ $EXECUTE_CS_CHECK == 'true' ]]; then php php-cs-fixer.phar fix -v --diff --dry-run ; fi
  
after_script:
  - php vendor/bin/coveralls -v
    