<?php

namespace LosMiddleware\RateLimit;

use Zend\ServiceManager\ServiceManager;
use Zend\ServiceManager\Config;

/**
 * Generated by PHPUnit_SkeletonGenerator on 2015-11-02 at 17:06:44.
 */
class RateLimitFactoryTest extends \PHPUnit_Framework_TestCase
{
    /**
     * @var RateLimitFactory
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp()
    {
        $this->object = new RateLimitFactory();
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown()
    {
    }

    /**
     * @covers LosMiddleware\RateLimit\RateLimitFactory::__invoke
     */
    public function test__invoke()
    {
        $container = new ServiceManager(new Config([]));
        $container->setService('config', []);
        $this->assertInstanceOf(RateLimit::class, $this->object->__invoke($container));
    }
}
