<?php

namespace LosMiddleware\RateLimit\Storage;
use PHPUnit\Framework\TestCase;

/**
 * Generated by PHPUnit_SkeletonGenerator on 2015-11-02 at 17:06:44.
 */
class ApcStorageTest extends TestCase
{
    /**
     * @var RateLimitFactory
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp()
    {
        if (!getenv('TESTS_APC_ENABLED')) {
            $this->markTestSkipped('Enable TESTS_APC_ENABLED to run this test');
        }
        $this->object = new ApcStorage(true);
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown()
    {
    }

    /**
     * @covers LosMiddleware\RateLimit\Storage\ApcStorage::__construct
     * @covers LosMiddleware\RateLimit\Storage\ApcStorage::set
     * @covers LosMiddleware\RateLimit\Storage\ApcStorage::get
     */
    public function testSetGet()
    {
        if (!getenv('TESTS_APC_ENABLED')) {
            $this->markTestSkipped('Enable TESTS_APC_ENABLED to run this test');
        }
        $this->object->set('key', 'value');
        $this->assertSame('value', $this->object->get('key'));
        $this->assertSame('not', $this->object->get('nokey', 'not'));
    }
}
