<?php

namespace LosMiddleware\RateLimit\Storage;

/**
 * Generated by PHPUnit_SkeletonGenerator on 2015-11-02 at 17:06:44.
 */
class ArrayStorageTest extends \PHPUnit_Framework_TestCase
{
    /**
     * @var RateLimitFactory
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp()
    {
        $this->object = new ArrayStorage();
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown()
    {
    }

    /**
     * @covers LosMiddleware\RateLimit\Storage\ArrayStorage::__construct
     * @covers LosMiddleware\RateLimit\Storage\ArrayStorage::set
     * @covers LosMiddleware\RateLimit\Storage\ArrayStorage::get
     */
    public function testSetGet()
    {
        $this->object->set('key', 'value');
        $this->assertSame('value', $this->object->get('key'));
        $this->assertSame('not', $this->object->get('nokey', 'not'));
    }
}
