<?php

namespace LosMiddleware\RateLimit\Storage;

use org\bovigo\vfs\vfsStream;

/**
 * Generated by PHPUnit_SkeletonGenerator on 2015-11-02 at 17:06:44.
 */
class FileStorageTest extends \PHPUnit_Framework_TestCase
{
    /**
     * @var RateLimitFactory
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp()
    {
        vfsStream::setup('home');
        $file = vfsStream::url('home/static.log');
        file_put_contents($file, 'The new contents of the file');
        $this->object = new FileStorage($file, true);
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown()
    {
    }

    /**
     * @covers LosMiddleware\RateLimit\Storage\FileStorage::__construct
     * @covers LosMiddleware\RateLimit\Storage\FileStorage::set
     * @covers LosMiddleware\RateLimit\Storage\FileStorage::get
     * @covers LosMiddleware\RateLimit\Storage\FileStorage::getFile
     */
    public function testSetGet()
    {
        $this->object->set('key', 'value');
        $this->assertSame('value', $this->object->get('key'));
        $this->assertSame('not', $this->object->get('nokey', 'not'));
    }

    /**
     * @covers LosMiddleware\RateLimit\Storage\FileStorage::__construct
     * @covers LosMiddleware\RateLimit\Storage\FileStorage::set
     * @covers LosMiddleware\RateLimit\Storage\FileStorage::get
     * @covers LosMiddleware\RateLimit\Storage\FileStorage::getFile
     */
    public function testCanOverwride()
    {
        $this->object->set('key', 'value');
        $this->assertSame('value', $this->object->get('key'));
        $this->object->set('key', 'value2');
        $this->assertSame('value2', $this->object->get('key'));
    }
}
